name: Handle Issues
on:
  issues:
    types:
      - opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  IS_STORY: ${{ contains(github.event.issue.labels.*.name, 'story') }}
  CREATED_BY_ADMIN: ${{ github.event.issue.user.login == 'Madeline-Ellingson' }}
  NUMBER: ${{ github.event.issue.number }}
  BODY: "This issue was automatically deleted because it was submitted by a non-admin user. Please use the Bug Report or Feature Request template instead."

jobs:
  handle-issues:
    name: Handle Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Comment on the issue if it is a story and was NOT created by an admin
        if: ${{ env.IS_STORY == 'true' && env.CREATED_BY_ADMIN == 'false' }}
        run: gh issue comment "$NUMBER" --body "$BODY"
      - name: Close if the issue is a story and was NOT created by an admin
        if: ${{ env.IS_STORY == 'true' && env.CREATED_BY_ADMIN == 'false' }}
        run: gh issue close "$NUMBER"
      - name: Add issue to the project
        if: ${{ env.CREATED_BY_ADMIN == 'true' || env.IS_STORY == 'false' }}
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Madeline-Ellingson/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

