name: Handle Issues
on:
  issues:
    types:
      - opened
jobs:
  handle-issues:
    name: Handle Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      STORY_CREATED_BY_ADMIN: ${{ contains(github.event.issue.labels.*.name, 'story') && github.event.issue.user.login == 'Madeline-Ellingson' }}
      NUMBER: ${{ github.event.issue.number }}
      BODY: "This issue was automatically deleted because it was submitted by a non-admin user. Please use the Bug Report or Feature Request template instead."

    steps:
      - name: Comment on the issue if it is a story and was NOT created by an admin
        if: ${{ !(contains(github.event.issue.labels.*.name, 'story') && github.event.issue.user.login == 'Madeline-Ellingson') }}
        run: gh issue comment "$NUMBER" --body "$BODY"
      - name: Close if the issue is a story and was NOT created by an admin
        if: ${{ !(contains(github.event.issue.labels.*.name, 'story') && github.event.issue.user.login == 'Madeline-Ellingson') }}
        run: gh issue close "$NUMBER"
      - name: Add issue to the project
        if: ${{ (contains(github.event.issue.labels.*.name, 'story') && github.event.issue.user.login == 'Madeline-Ellingson') || !contains(github.event.issue.labels.*.name, 'story') }}
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Madeline-Ellingson/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}
